/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.AnimalController;
import controller.ClientController;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Animal;
import model.Client;

/**
 *
 * @author user
 */
public class AnimalPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnimalPanel
     */
    private AnimalController animalController = new AnimalController();
    private ClientController clientController = new ClientController();
    private String[] gender = {"Betina","Jantan"};
    private DefaultComboBoxModel comboModelGender = new DefaultComboBoxModel(gender);
    private List<Animal> animals;
    private Animal animal;
    private String selectedId = null;
    private int limit = 10;
    private int offset = 0;
    
    public AnimalPanel() throws SQLException {
        initComponents();
        loadAnimalsData(limit,offset);
        clearForm();

    }
    
    private void loadAnimalsData(int limit, int offset) throws SQLException {
        animals = animalController.getAll();
        List<Animal> animals_temp = animalController.getSome(limit, offset);
        String[][] data = new String[animals_temp.size()][6];
        
        for (int i=0; i<animals_temp.size(); i++) {
            data[i][0] = animals_temp.get(i).getIdAnimal();
            data[i][1] = animals_temp.get(i).getType();
            data[i][2] = String.valueOf(animals_temp.get(i).getAge());
            data[i][3] = String.valueOf(animals_temp.get(i).getWeight());
            Boolean gender_temp = animals_temp.get(i).getGender();
            if (gender_temp == false) {
                data[i][4] = gender[0];
            } else {
                data[i][4] = gender[1];
            }
            Client ownerTemp = animals_temp.get(i).getClient();
            data[i][5] = (ownerTemp != null && ownerTemp.getIdClient() != null && !ownerTemp.getIdClient().isEmpty())
                    ? ownerTemp.getIdClient() : "(none)";
        }
        
        String[] column = {"ID","Type","Age","Weight","Gender","Owner Client ID"};
        jTableAnimal.setModel(new DefaultTableModel(data,column) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }  
        });
        
        jLabelTotal.setText(String.valueOf(animals.size()));
    }
    
    private void clearForm() {
        jTextFieldType.setText("");
        jTextFieldAge.setText("");
        jTextFieldWeight.setText("");
        jTextFieldClientID.setText("");
        animal = new Animal();
        jTableAnimal.clearSelection();
        selectedId = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelClientID = new javax.swing.JLabel();
        jTextFieldClientID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnimal = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonNext = new javax.swing.JButton();
        jButtonPrev = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelPage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldType = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldWeight = new javax.swing.JTextField();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jButtonSave.setBackground(new java.awt.Color(0, 204, 0));
        jButtonSave.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(this::jButtonSaveActionPerformed);

        jButtonDelete.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDelete.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonCancel.setBackground(new java.awt.Color(255, 204, 0));
        jButtonCancel.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(this::jButtonCancelActionPerformed);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jTableAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Age", "Weight", "Gender"
            }
        ));
        jTableAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAnimalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableAnimalMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAnimal);

        jLabel5.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Tabel Animal");

        jButtonSearch.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(this::jButtonSearchActionPerformed);

        jTextFieldSearch.addActionListener(this::jTextFieldSearchActionPerformed);

        jButtonNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNext.setText("Next >>");
        jButtonNext.addActionListener(this::jButtonNextActionPerformed);

        jButtonPrev.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrev.setText("<< Previous");
        jButtonPrev.addActionListener(this::jButtonPrevActionPerformed);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Search :");

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel7.setText("Page  : ");

        jLabelPage.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelPage.setText("1");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total Animal :");

        jLabelTotal.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonPrev)
                                .addGap(207, 207, 207)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTotal)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jLabel9)
                    .addComponent(jLabelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrev)
                    .addComponent(jButtonNext)
                    .addComponent(jLabel7)
                    .addComponent(jLabelPage))
                .addContainerGap())
        );

        jButtonRefresh.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRefresh.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(this::jButtonRefreshActionPerformed);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Type");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Weight");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Age");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 28)); // NOI18N
        jLabel1.setText("ADD ANIMAL");

        jTextFieldAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTextFieldAge.addActionListener(this::jTextFieldAgeActionPerformed);

        jTextFieldType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTextFieldType.addActionListener(this::jTextFieldTypeActionPerformed);

        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Gender");

        jTextFieldWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTextFieldWeight.addActionListener(this::jTextFieldWeightActionPerformed);

        jLabelClientID.setFont(new java.awt.Font("Ebrima", 1, 16));
        jLabelClientID.setForeground(new java.awt.Color(51, 51, 51));
        jLabelClientID.setText("Owner Client ID");

        jTextFieldClientID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jComboBoxGender.setModel(comboModelGender);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/paw-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jButtonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(230, 230, 230))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelClientID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldClientID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientID)
                    .addComponent(jTextFieldClientID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonDelete))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        String type = jTextFieldType.getText();
        String age = jTextFieldAge.getText();
        String weight = jTextFieldWeight.getText();
        String clientId = jTextFieldClientID.getText().trim();
        Boolean gender = null;
        if (jComboBoxGender.getSelectedItem().toString().equals("Jantan")) {
            gender = true;
        } else {
            gender = false;
        }
        
        if (type.isEmpty() || age.isEmpty() || weight.isEmpty() || clientId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all field, including the Owner Client ID!");
            return;
        }
        
        Client owner = clientController.getById(clientId);
        if (owner == null) {
            JOptionPane.showMessageDialog(this, "No client found with ID '" + clientId + "'. Please enter a valid Client ID!");
            return;
        }
        
        animal = new Animal("",type,Integer.valueOf(age),Double.valueOf(weight),gender,owner);
        
        if (selectedId != null) {
            try {
                animalController.update(animal, selectedId);
                JOptionPane.showMessageDialog(this, "Animal updated successfully!");
            } catch (SQLException ex) {
                System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                JOptionPane.showMessageDialog(this, "Failed to update animal!");
            }
        } else {
            try {
                animalController.create(animal);
            } catch (SQLException ex) {
                System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                JOptionPane.showMessageDialog(this, "Failed to create animal!");
            }
        }
        
        clearForm();
        try {
            loadAnimalsData(limit, offset);
        } catch (SQLException ex) {
            System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedId != null) {
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure want to delete this animal?", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    animalController.delete(selectedId);
                } catch (SQLException ex) {
                    System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                clearForm();
                try {
                    loadAnimalsData(limit,offset);
                    JOptionPane.showMessageDialog(this, "Animal deleted successfull!");
                } catch (SQLException ex) {
                    System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    JOptionPane.showMessageDialog(this, "Deleted unsuccessfull!");
                }
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        try {
            // TODO add your handling code here:
            loadAnimalsData(limit, offset);
        } catch (SQLException ex) {
            System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jTextFieldTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTypeActionPerformed

    private void jTextFieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWeightActionPerformed

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
        if (offset >= limit) {
            try {
                offset -= limit;
                loadAnimalsData(limit, offset);
                jLabelPage.setText("Page : "+String.valueOf((offset/limit)+1));
                clearForm();
            } catch (SQLException ex) {
                System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
        }
    }//GEN-LAST:event_jButtonPrevActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        int size = animals.size();
        if (offset + limit < size) {
            try {
                offset += limit;
                loadAnimalsData(limit, offset);
                jLabelPage.setText("Page : "+String.valueOf((offset/limit)+1));
                clearForm();
            } catch (SQLException ex) {
                System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jTableAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnimalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableAnimalMouseClicked

    private void jTableAnimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnimalMousePressed
        // TODO add your handling code here:
        int selectedRow = jTableAnimal.getSelectedRow();
        if (selectedRow != -1) {
            selectedId = jTableAnimal.getValueAt(selectedRow, 0).toString();
            jTextFieldType.setText(jTableAnimal.getValueAt(selectedRow, 1).toString());
            jTextFieldAge.setText(jTableAnimal.getValueAt(selectedRow, 2).toString());
            jTextFieldWeight.setText(jTableAnimal.getValueAt(selectedRow, 3).toString());
            jComboBoxGender.setSelectedItem(jTableAnimal.getValueAt(selectedRow, 4).toString());
            String ownerId = jTableAnimal.getValueAt(selectedRow, 5).toString();
            jTextFieldClientID.setText("(none)".equals(ownerId) ? "" : ownerId);
        }
    }//GEN-LAST:event_jTableAnimalMousePressed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String id = jTextFieldSearch.getText();
        Boolean found = false;
        int size = animals.size();
        int index = 0;
        for (Animal animal : animals) {
            if (id.equals(animal.getIdAnimal())) {
                found = true;
                break;
            }
            index++;
        }
        if (found) {
            try {
                index = ((size-1)-index);
                int page = (index/limit)+1;
                int row = index%limit;
                jLabelPage.setText("Page : "+String.valueOf(page));
                offset = (index/limit)*limit;
                loadAnimalsData(limit, offset);
                jTableAnimal.setRowSelectionInterval(row, row);
                
                int selectedRow = jTableAnimal.getSelectedRow();
                selectedId = jTableAnimal.getValueAt(selectedRow, 0).toString();
                jTextFieldType.setText(jTableAnimal.getValueAt(selectedRow, 1).toString());
                jTextFieldWeight.setText(jTableAnimal.getValueAt(selectedRow, 3).toString());
                jTextFieldAge.setText(jTableAnimal.getValueAt(selectedRow, 2).toString());
                jComboBoxGender.setSelectedItem(jTableAnimal.getValueAt(selectedRow, 4).toString());
                String ownerId = jTableAnimal.getValueAt(selectedRow, 5).toString();
                jTextFieldClientID.setText("(none)".equals(ownerId) ? "" : ownerId);
            } catch (SQLException ex) {
                System.getLogger(AnimalPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                clearForm();
            }
        } else {
            JOptionPane.showMessageDialog(this, "'"+id+"' "+"doesn't exist!");
            jTextFieldSearch.setText("");
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientID;
    private javax.swing.JLabel jLabelPage;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAnimal;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldClientID;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldType;
    private javax.swing.JTextField jTextFieldWeight;
    // End of variables declaration//GEN-END:variables
}
